name: Continuous deployment
on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

# Allow only one concurrent deployment, cancel ongoing ones.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - uses: actions/checkout@v3

      - run: trunk build --release

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist